### ISSUE TITLE
Thank you!!

### ISSUE THREAD

**Issue by smuun** [heyyeh12/zoom_cc#1]
Hey! Just wanted to thank you for making this available; my grandfather needed a way to get subtitles on Zoom and this is perfect.

**Comment by heyyeh12** [comment]
Glad you found it useful! I originally put this together this to help my grandfather too :)

We ran into limitations with making the text large enough for him to read though, so now he uses a tablet next to his computer running either [Otter](https://otter.ai/) or [Live Transcribe](https://play.google.com/store/apps/details?id=com.google.audio.hearing.visualization.accessibility.scribe&hl=en_US&gl=US). As a bonus, it's easier for him to scroll back to catch conversation that went by too quickly, and it's a tool he can use for in-person conversations too. Thought I would mention it in case that's an option that would work better for you
